### PR TITLE
JENKINS-64195 Make plugin work on Jenkins >=2.266

### PR DESCRIPTION
**Pull request by timja**

### CODE REVIEW

**Review by fqueiruga — APPROVED** [review]
Haven't tested, code looks good

**Comment by timja** [comment]
@xuzhang3 can you take a look please, more info in https://github.com/jenkinsci/azure-vm-agents-plugin/pull/190#issuecomment-728090485

**Comment by xuzhang3** [comment]
@timja I don't have time for this PR this week.

**Comment by timja** [comment]
> @timja I don't have time for this PR this week.

no problem

**Comment by timja** [comment]
@xuzhang3 you got time to check this soon?

**Comment by timja** [comment]
@xuzhang3 or @yuwzho any chance you have time for at least this PR soon?

Most of the azure plugins are broken and need this plugin and library updated first.

Unfortunately the library is masked so every plugin needs updating and just updating this plugin isn't enough 😢

**Comment by xuzhang3** [comment]
LGTM

**Pull request merged**
