### PR TITLE
Upgrade baseline, java 8, fix maven build

### PR DESCRIPTION
**Pull request by timja**
Baseline: 2.89.4 to match https://github.com/jenkinsci/windows-azure-storage-plugin/blob/dev/pom.xml#L20

There was a bug in the parent pom version this was at, to do with the findbugs maven plugin that was preventing me from building this project:
```
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.3:findbugs (findbugs) on project azure-commons-parent: Unable to parse configuration of mojo org.codehaus.mojo:findbugs-maven-plugin:3.0.3:findbugs for parameter pluginArtifacts: Cannot assign configuration entry 'pluginArtifacts' with value '${plugin.artifacts}' of type java.util.Collections.UnmodifiableRandomAccessList to property of type java.util.ArrayList -> [Help 1]
```

Upgrading the parent pom fixed this

~half of the azure plugins are already on this jenkins version or above

the rest are either not really active or can be upgraded the next time they need a bump

If anyone is still on such an old version of java / jenkins they are highly unlikely to be updating plugins, most plugins now have a java 8 baseline...

### CODE REVIEW

**Comment by timja** [comment]
@gavinfish

**Comment by gavinfish** [comment]
@timja I know something about that error here. It should be something wrong between specific maven version and findbugs plugin version. You can set findbugs plugin version to 3.0.5 in plugins section to fix this issue. It is no matter with Jenkins baseline. I prefer to set the baseline here as 2.60.1 which is the first Jenkins LTS release that requires Java 8 to run.

**Comment by timja** [comment]
I get that, but shouldn't need to do that, upgrading parent pom is easier,
I've changed it to 2.60.1

**Review by gavinfish — APPROVED** [review]
LGTM

**Pull request merged**
